version: '2'
services:
  proxy:
    image: nginx:1.13.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    links:
      - backend
      - frontend
    restart: always
    networks:
      navigation-for-web:
        ipv4_address: 10.5.0.5
  frontend: 
    image: node:6.11.3
    expose:
      - "4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    networks:
      navigation-for-web:
        ipv4_address: 10.5.0.4
  backend:
    image: openjdk:8-jdk-alpine
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ./mvnw -Pprod spring-boot:run
    links: 
      - mysql
    networks:
      navigation-for-web: 
        ipv4_address: 10.5.0.3
  mysql-data:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: mysql-datastore
  mysql:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: navigation_for_web
       MYSQL_USER: umesystems
       MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: mysql-db
    volumes_from:
      - mysql-data
    networks:
      navigation-for-web: 
        ipv4_address: 10.5.0.2
networks:
  navigation-for-web:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1