version: '2'
services:
  proxy:
    image: nginx:1.13.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/prod:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    links:
      - backend
      - frontend
    restart: always

  frontend:
    image: nginx:1.13.5
    expose:
      - "80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend_nginx/logs:/var/log/nginx
      - ./frontend_nginx/conf.d:/etc/nginx/conf.d
    restart: always

  webpack: 
    image: node:6.11.3
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "yarn install && npm run build"

  backend:
    image: openjdk:8-jdk-alpine
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "./mvnw clean && ./mvnw -Pprod spring-boot:run -Drun.profiles=prod"
      - redis

  redis:
    image: redis:3.2.9
    ports:
      - 6379:6379