version: '2'
services:
  proxy:
    image: nginx:1.13.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    links:
      - backend
      - frontend
    restart: always

  frontend:
    image: nginx:1.13.5
    expose:
      - "80"
      - "433"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx_frontend/logs:/var/log/nginx
      - ./nginx_frontend/conf.d:/etc/nginx/conf.d
    restart: always

  webpack: 
    image: node:6.11.3
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "yarn install && npm run build"

  backend:
    image: openjdk:8-jdk-alpine
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "./mvnw clean && ./mvnw -Pprod spring-boot:run -Drun.profiles=prod"
    links: 
      - mysql

  mysql-data:
    image: busybox
    volumes:
      - /var/lib/mysql
    container_name: mysql-datastore

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: navigation_for_web_prod
       MYSQL_USER: umesystems
       MYSQL_PASSWORD: password
       TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    container_name: mysql-db
    volumes_from:
      - mysql-data